### ISSUE TITLE
Exception při neexistujícím klíči

### ISSUE THREAD

**Issue by zvitek** [Tharos/Schematic#9]
Ahoj,
předem děkuji za vyčištění mého asociativního bordelu 👍 

Mám definované schéma:

```php
/**
 * @property-read int    $id
 * @property-read string $name
 * @property-read string $description
 */
class BranchSchema extends Entry
{
}
```
s kterým kdekoliv následně pracuji:

```php
$this->branchSchema = new BranchSchema($this->values);
$this->branchSchema->name;
$this->branchSchema->id;
```

Co ale dělat s klíči, které sice schéma obsahuje, ale nejsou povinné?
Pokud se v běhu zeptám na 

```php
$this->branchSchema->description;
```

tak dostanu exception což je pocohpitelné ale nevyhovující. Pokud se (základně) zeptám na 

```php
if($this->branchSchema->description) {
    $this->branch->setDescription($this->branchSchema->description);
}
```
tak nechci exception ale ideálně null value nebo hodnotu odpovídající typu proměnné, je to možné nebo myslím na blbosti a naspat si nad Entry nejaká wrapper?

Díky

**Comment by Tharos** [comment]
Ahoj,

myslím, že by ti to mohl vyřešit prostý `isset`:

```php
if(isset($this->branchSchema->description)) {
    $this->branch->setDescription($this->branchSchema->description);
}
```

Eventuálně si můžeš udělat potomka `Entry`, který čtení chybějících prvků pole bude umožňovat a vracet třeba `NULL`:

```php


/**
 * @param string $name
 * @return mixed
 */
public function __get($name)
{
	try {
		return parent::__get($name);

	} catch (InvalidArgumentException $e) {
		return NULL;
	}
}
```

V základu to tak není, protože je to takové dvousečné… Neúplná pole umí být zrádná, vždycky je lepší tam ty prvky mít. :) Pokud dostanu `NULL`, znamená to, že ta data chybí v úložišti, anebo že se z něj pouze nenačetly? Atp.

**Comment by zvitek** [comment]
Jasný, to je úplně v pohodě, jenom to byla taková idea :)

Díky :)
